### PR TITLE
PKCE with dynamic secret

### PR DESCRIPTION
**Pull request by raphaellondner-okta**
@leastprivilege done. Sorry for the delay and let me know if you need anything else.

### CODE REVIEW

**Comment by leastprivilege** [comment]
As you can see this did not build - you need to merge with my current version dev.

**Comment by leastprivilege** [comment]
nevermind - I merged it manually. Could you check if this works for you?

**Comment by raphaellondner-okta** [comment]
Hi @leastprivilege, thank you for merging it manually. I'll review it once I have another functioning environment (my previous Xamarin install broke my laptop network adapters so I'm waiting to get another machine ready with VS2015, Xamarin...). Hopefully will be able to get back to you by EOW.

**Comment by raphaellondner-okta** [comment]
OK, I've tested this new build and overall, it wokrs for me with 2 restrictions:
1. the ID token is signed with the first JsonWebKey retrieved from the OIDC client metadata (not always the case)
2. there is no refresh token (issue with RefeshTokenHandler in OidcClient)

My next task is to fix the signing key issue (restriction#1). Should I update DefaultIdentityTokenValidator or create another class implementing IIdentityTokenValidator?

Next I'll have to make sure RefeshTokenHandler works with a dynamic client secret (might require modifications to the IdentityModel library)

**Pull request closed without merging**
