### PR TITLE
Moved to project.json and .NET Core

### PR DESCRIPTION
**Pull request by xperiandri**
Do not merge until UWP supports referencing xproj

### CODE REVIEW

**Comment by xperiandri** [comment]
Do not merge until UWP supports referencing project.json

**Comment by leastprivilege** [comment]
Why? This is a functional PCL right now and project.json is soon to be deprecated.

I'd rather wait and move it to whatever will replace project.json

**Comment by xperiandri** [comment]
Where have you heard that project.json will be deprecated?
On the NuGet repo official MS developers suggest to move all the projects except classic ASP.NET to project.json
See https://github.com/NuGet/Home/issues/2368

**Comment by leastprivilege** [comment]
project.json will go away and MS will move back to csproj. Google for it.

**Comment by leastprivilege** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by xperiandri** [comment]
As I supposed it is not deprecated in general meaning.
Read https://github.com/NuGet/Home/issues/2368#issuecomment-233466817

**Comment by leastprivilege** [comment]
not sure what "general meaning" means - but project.json will be removed in favour of MSBuild and .csproj. This will happen in one of the next tooling updates.

Do you see value in moving to an "intermediate" project system?

**Comment by xperiandri** [comment]
If I will add a UWP, Win8.1 and WP8.1 targets, it will be much simpler with xproj than with csproj

**Comment by leastprivilege** [comment]
It already supports all those targets - no?

My point is - why move a working project to a new format that will go away soon - we will wait what comes after project.json

**Comment by xperiandri** [comment]
If I implement `Windows.Web.Http.IHttpFIlter` for `Windows.Web.Http.HttpClient` I will need to target either PCL Win81+WP81 or each platform separately.

**Comment by leastprivilege** [comment]
Have you tested that this version still works on all required platforms?

Xamarin iOS, Android, Desktop .NET and UWP?

**Comment by leastprivilege** [comment]
As an exercise - we should first make 

https://github.com/IdentityModel/IdentityModelv2

run on all target platforms again.

and then go from there.

**Comment by xperiandri** [comment]
> As an exercise - we should first make 
> https://github.com/IdentityModel/IdentityModelv2

Agree

> Have you tested that this version still works on all required platforms?
> Xamarin iOS, Android, Desktop .NET and UWP?

Do you mean the resulting binnaries produced from xproj?

**Comment by leastprivilege** [comment]
> > Do you mean the resulting binnaries produced from xproj?

yes

**Comment by xperiandri** [comment]
No, I did not.
After I realized that I can't reference xproj from csproj (UWP in particular) I left that idea for some time.

**Comment by leastprivilege** [comment]
right - I think it is too early in many ways. 

leaving it for now.

**Pull request closed without merging**
